### ISSUE TITLE
Offset failed, scanning on game pass version

### ISSUE THREAD

**Issue by ddf420** [Gamergotten/Infinite-runtime-tagviewer#108]
IRTV still not very usable yet

**Comment by TempAccountNull** [comment]
Do me a favor. Attempt to get a .exe dump with UWPDumper here: https://github.com/Wunkolo/UWPDumper and please report back, otherwise you can use x64Dbg -> Plugins Tab ->Scylla and select the HaloInfinite.exe and try to dump it and link it here.

**Comment by ddf420** [comment]
UWPDumper seems to not work, Halo Infinite closes itself upon being dumped.
Either dumping crashed it or some sort of anti dumping. 
Tried freezing the program but it does not work 

Scylla does not pick up the program at all
Really need assistance here. Dumping seems not be very possible.

**Comment by Z-15** [comment]
This issue should've been resolved with the pointer update. From the times I've encountered this issue, it was because the incorrect base address was set in the settings. The scan will either replace that address or say infinite can't be found. If infinite can't be found you need to clear the pointer value and attempt to load again.

This issue is a couple weeks old with no traffic. I'm closing this for now, if the issue persists please open another ticket.
