### ISSUE TITLE
Tags won't poke.

### ISSUE THREAD

**Issue by TWELVEG8J** [Gamergotten/Infinite-runtime-tagviewer#109]
I'm using the new version. Anti-Virus Disabled, Halo Infinite instance running, press load, it loads the instance, but whenever I press Poke, nothing happens. I press reload, still nothing. The Tags just simply won't poke.

**Comment by Connor-jt** [comment]
tempaccountnull recently altered the pointers, you would have to check in with the other guys to make sure he didnt break it haha

seeing as the other guys already pushed the new pointers (i think, unless there was another small update after the big season 2 one)

**Comment by TWELVEG8J** [comment]
Can you tell him to fix it? It'd mean a thousand- One halo modder to another.

**Comment by Connor-jt** [comment]
wait uh, i kinda forgot how the tool worked there (although im still not 100% certain)

failing to poke is usually user error
if the tool can load & read tags then the tool is doing its job correctly (when you hit "load tags" you should see this giant list of tag groups show up on the left side panel of the main window, if no tags show up, then it failed to load them, probably due to an error in the tool)

writing them is the users job, its possible you are either trying to poke things to the wrong tags (each weapon has two different tags, one for campaign and one for multiplayer), or, the things you are trying to poke simply do not do what you're expecting them to do, and thus you are not seeing the changes that you expect to see

if thats not the case, are you attempting to use other users mods? as there has apparently been some issues with the latest version of halo infinite having restructured some of its tags & breaking the mods

**Comment by TempAccountNull** [comment]
> tempaccountnull recently altered the pointers, you would have to check in with the other guys to make sure he didnt break it haha
> 
> seeing as the other guys already pushed the new pointers (i think, unless there was another small update after the big season 2 one)

The only pointer I fixed, was the original one where you didn't have to wait for it to scan the tag instances string. That is all I have fixed so it loads instantly. I always triple check my work on my end before pushing updates and have been since I have became a collaborator here.

**Comment by TempAccountNull** [comment]
Laugh all you want. I'm closing this.
