### ISSUE TITLE
Onscreen Overlay for Selected Tags

### ISSUE THREAD

**Issue by Finatra** [Gamergotten/Infinite-runtime-tagviewer#111]
It would be helpful to monitor values in real time during gameplay.

Having live values overlaid on top of the game would be helpful when investigating tag behavior.
Each frame of recorded gameplay would show the values at that instant.

**Comment by Gamergotten** [comment]
im not familiar with any tags that actually update during gameplay, the only tags that i know that update are like the player customization ones where it changes when loading in campaign - and thats only because its overwriting that tag with the campaign's one

however that does sound like a pretty neat feature - even if those values would only update when you poke them

**Comment by Finatra** [comment]
Sorry, that's my mistake. 🤣 
I have to admit, I can't actually USE the tag viewer right now since I'm confined to console.

My impression is that the tool only works while Infinite is running.
So, I figured it was showing content in memory.

🙄

**Comment by Gamergotten** [comment]
the point of the tool is to view/edit tag definitions (tag definitions as in, the values that a specific tag consists/ is constructed of) 
tag being an entity of a specific type, for example: the warthog is a tag, changing the tag definitions for the warthog will affect all warthogs in the game)
im not even sure if its possible to edit singular instances of tags, that might be something worth looking into sometime

**Comment by Z-15** [comment]
Seems more like a recommendation than an issue. Also, no traffic in 21 days, so I'm closing.
