### ISSUE TITLE
Will this project continue?

### ISSUE THREAD

**Issue by Nighterlev** [Gamergotten/Infinite-runtime-tagviewer#142]
With Halo Infinite now using EAC, will this project continue to be updated?  Or is this the EOL of the project?
Still useful for exploring old builds of Halo Infinite, but I am curious what the status of this project is now that EAC is being applied.

**Comment by Connor-jt** [comment]
no sorry, this project hasn't been updated in a long while and the state of the game has long deterred me from wanting to do anything else with the tool

all of my notes on the EAC implementation were shared in issue #138 (preferably continue any EAC conversation there, unless its quotes to this response)

and a list of alternate (possibly functioning) tools were listed [here](https://github.com/Gamergotten/Infinite-runtime-tagviewer/issues/140#issuecomment-1965689764)
which should circumvent the EAC for the time being (explained in the first link), although i cant guarantee that it wont put you on 343's watch/ban list or something

fixing the tool is up to 343, cause they apparently did not consult a single person involved in halo infinite modding
the only word i ever got (from a 'devs' friend) was that they were trying to come up with ways of blocking this tool, and that was like 2 years ago

i really could not tell you why they specified that 'EAC is not active in .. forges edit mode', i haven't tested myself but i can almost garantee that that is not in any way true
(obviously its not active in campaign because its not even installed for campaign!!)

the only mechanism that infinite's EAC really has over cheats is the memory address obfuscation thing, where windows will just return nothing when memory reads are requested from the halo infinite process (im not actually sure on the specifics but thats what i think decently explains it)
and i think its highly unlikely that it just turns off when you go into forge mode, or else you would just beable to inject cheats into the game while playing forge and go back to the menu

so from that i can pretty well assume that whoever is now incharge of their anti cheat stuff has no clue what they're doing, considering most of what they mentioned in the EAC update was just not true 
nor has the EAC stopped any cheaters i believe, they've already updated their cheats to work around it

343 are totally welcome to reach out, but it really does not seem to be in their interests to support any part of the halo community that doesn't exclusively slave away for 1000's of hours to spoonfeed them new content to put into matchmaking so they can boast to have so many more maps than at launch

**Comment by Connor-jt** [comment]
oh i dont think i wrote it down anywhere, so for preservations sake you can still dump the tag struct xmls that all those module file reading/editing tools use, you just target the unprotected lan server halo infinite processes instead of the actual game one (doing this however may require editing some code or if you can get the lan server exe running by itself i think)
